import React from 'react'
import Script from 'next/script'

const contact = () => {
  return (
    <div>
        <Script>
            {`
            alert("welcome to contact page")
            `}
        </Script>
      i am contact
    </div>
  )
}

export default contact

export const metadata = {
    title: "Contact Facebook",
    description: "Generated by create next app",
  };